# Template for new Alembic revision files.

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '329d6c4bcdc1'
down_revision = '86ebf8ea7442'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rules', sa.Column('subcategory_id', sa.Integer(), nullable=True))
    op.add_column('rules', sa.Column('subcategory', sa.String(length=80), nullable=True))
    op.create_index(op.f('ix_rules_subcategory_id'), 'rules', ['subcategory_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rules_subcategory_id'), table_name='rules')
    op.drop_column('rules', 'subcategory')
    op.drop_column('rules', 'subcategory_id')
    # ### end Alembic commands ###
