# Template for new Alembic revision files.

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '38bb55910fb1'
down_revision = 'd5ff957f241b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experts', 'audit_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experts', sa.Column('audit_status', sa.VARCHAR(length=20), nullable=False))
    # ### end Alembic commands ###
