# Template for new Alembic revision files.

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '8d90a00d98b0'
down_revision = '329d6c4bcdc1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'draw_applications',
        sa.Column('backup_count', sa.Integer(), nullable=False, server_default='0'),
    )
    op.drop_column('rules', 'backup_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'rules',
        sa.Column('backup_count', sa.INTEGER(), nullable=False, server_default='0'),
    )
    op.drop_column('draw_applications', 'backup_count')
    # ### end Alembic commands ###
