# Template for new Alembic revision files.

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '9c8923f9b8a1'
down_revision = 'c3a1e9f4b2aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rules', sa.Column('specialty_ids', sa.JSON(), nullable=True))
    op.add_column('rules', sa.Column('title_required_ids', sa.JSON(), nullable=True))
    op.add_column('rules', sa.Column('region_required_ids', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rules', 'region_required_ids')
    op.drop_column('rules', 'title_required_ids')
    op.drop_column('rules', 'specialty_ids')
    # ### end Alembic commands ###
