# Template for new Alembic revision files.

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'ce9efe7a70d0'
down_revision = '8d90a00d98b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expert_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expert_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expert_documents_doc_type'), 'expert_documents', ['doc_type'], unique=False)
    op.create_index(op.f('ix_expert_documents_expert_id'), 'expert_documents', ['expert_id'], unique=False)
    op.create_table('expert_specialties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expert_id', sa.Integer(), nullable=False),
    sa.Column('specialty_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('expert_id', 'specialty_id', name='uq_expert_specialty')
    )
    op.create_index(op.f('ix_expert_specialties_expert_id'), 'expert_specialties', ['expert_id'], unique=False)
    op.create_index(op.f('ix_expert_specialties_specialty_id'), 'expert_specialties', ['specialty_id'], unique=False)
    op.create_table('specialties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subcategory_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subcategory_id', 'name', name='uq_specialty_subcategory_name')
    )
    op.create_index(op.f('ix_specialties_subcategory_id'), 'specialties', ['subcategory_id'], unique=False)
    op.add_column('draw_applications', sa.Column('specialty_id', sa.Integer(), nullable=True))
    op.add_column('draw_applications', sa.Column('specialty', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_draw_applications_specialty'), 'draw_applications', ['specialty'], unique=False)
    op.create_index(op.f('ix_draw_applications_specialty_id'), 'draw_applications', ['specialty_id'], unique=False)
    op.add_column('experts', sa.Column('id_card_no', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_experts_id_card_no'), 'experts', ['id_card_no'], unique=True)
    op.add_column('rules', sa.Column('specialty_id', sa.Integer(), nullable=True))
    op.add_column('rules', sa.Column('specialty', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_rules_specialty'), 'rules', ['specialty'], unique=False)
    op.create_index(op.f('ix_rules_specialty_id'), 'rules', ['specialty_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rules_specialty_id'), table_name='rules')
    op.drop_index(op.f('ix_rules_specialty'), table_name='rules')
    op.drop_column('rules', 'specialty')
    op.drop_column('rules', 'specialty_id')
    op.drop_index(op.f('ix_experts_id_card_no'), table_name='experts')
    op.drop_column('experts', 'id_card_no')
    op.drop_index(op.f('ix_draw_applications_specialty_id'), table_name='draw_applications')
    op.drop_index(op.f('ix_draw_applications_specialty'), table_name='draw_applications')
    op.drop_column('draw_applications', 'specialty')
    op.drop_column('draw_applications', 'specialty_id')
    op.drop_index(op.f('ix_specialties_subcategory_id'), table_name='specialties')
    op.drop_table('specialties')
    op.drop_index(op.f('ix_expert_specialties_specialty_id'), table_name='expert_specialties')
    op.drop_index(op.f('ix_expert_specialties_expert_id'), table_name='expert_specialties')
    op.drop_table('expert_specialties')
    op.drop_index(op.f('ix_expert_documents_expert_id'), table_name='expert_documents')
    op.drop_index(op.f('ix_expert_documents_doc_type'), table_name='expert_documents')
    op.drop_table('expert_documents')
    # ### end Alembic commands ###
