# Template for new Alembic revision files.

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'd5ff957f241b'
down_revision = '439af1ba0dbf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_table('subcategories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'name', name='uq_subcategory_category_name')
    )
    op.create_index(op.f('ix_subcategories_category_id'), 'subcategories', ['category_id'], unique=False)
    op.add_column('draw_applications', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('draw_applications', sa.Column('subcategory_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_draw_applications_category_id'), 'draw_applications', ['category_id'], unique=False)
    op.create_index(op.f('ix_draw_applications_subcategory_id'), 'draw_applications', ['subcategory_id'], unique=False)
    op.add_column('experts', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('experts', sa.Column('subcategory_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_experts_category_id'), 'experts', ['category_id'], unique=False)
    op.create_index(op.f('ix_experts_subcategory_id'), 'experts', ['subcategory_id'], unique=False)
    op.add_column('rules', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_rules_category_id'), 'rules', ['category_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rules_category_id'), table_name='rules')
    op.drop_column('rules', 'category_id')
    op.drop_index(op.f('ix_experts_subcategory_id'), table_name='experts')
    op.drop_index(op.f('ix_experts_category_id'), table_name='experts')
    op.drop_column('experts', 'subcategory_id')
    op.drop_column('experts', 'category_id')
    op.drop_index(op.f('ix_draw_applications_subcategory_id'), table_name='draw_applications')
    op.drop_index(op.f('ix_draw_applications_category_id'), table_name='draw_applications')
    op.drop_column('draw_applications', 'subcategory_id')
    op.drop_column('draw_applications', 'category_id')
    op.drop_index(op.f('ix_subcategories_category_id'), table_name='subcategories')
    op.drop_table('subcategories')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
